In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
x=iris.data

In [7]:
y=iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
#class0-----> [1,0,0]
#class1----->[0,1,0]
#class2----->[0,0,1]

In [10]:
from tensorflow.keras.utils import to_categorical

In [11]:
y=to_categorical(y)

In [12]:
y.shape

(150, 3)

In [13]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [16]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
#max scaling means divide all values use  max value

In [19]:
scaler_object=MinMaxScaler()

In [20]:
scaler_object.fit(x_train)

MinMaxScaler()

In [21]:
scaled_x_train=scaler_object.transform(x_train)

In [22]:
scaled_x_test=scaler_object.transform(x_test)

In [23]:
scaled_x_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model=Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(scaled_x_train,y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.0791 - accuracy: 0.3800 - 611ms/epoch - 153ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0748 - accuracy: 0.3900 - 8ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0703 - accuracy: 0.4100 - 8ms/epoch - 2ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0659 - accuracy: 0.4200 - 8ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0613 - accuracy: 0.4300 - 10ms/epoch - 2ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0566 - accuracy: 0.4500 - 8ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0516 - accuracy: 0.5100 - 9ms/epoch - 2ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0466 - accuracy: 0.5700 - 8ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0416 - accuracy: 0.6100 - 11ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0363 - accuracy: 0.6300 - 7ms/epoch - 2ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0307 - accuracy: 0.6400 - 10ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0246 - accuracy: 0.6500 - 8ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0179 - accuracy: 0.660

Epoch 105/150
4/4 - 0s - loss: 0.4240 - accuracy: 0.9000 - 9ms/epoch - 2ms/step
Epoch 106/150
4/4 - 0s - loss: 0.4209 - accuracy: 0.9100 - 8ms/epoch - 2ms/step
Epoch 107/150
4/4 - 0s - loss: 0.4183 - accuracy: 0.9200 - 8ms/epoch - 2ms/step
Epoch 108/150
4/4 - 0s - loss: 0.4162 - accuracy: 0.9300 - 9ms/epoch - 2ms/step
Epoch 109/150
4/4 - 0s - loss: 0.4147 - accuracy: 0.9100 - 9ms/epoch - 2ms/step
Epoch 110/150
4/4 - 0s - loss: 0.4115 - accuracy: 0.9100 - 13ms/epoch - 3ms/step
Epoch 111/150
4/4 - 0s - loss: 0.4087 - accuracy: 0.9100 - 9ms/epoch - 2ms/step
Epoch 112/150
4/4 - 0s - loss: 0.4059 - accuracy: 0.9200 - 10ms/epoch - 2ms/step
Epoch 113/150
4/4 - 0s - loss: 0.4022 - accuracy: 0.9300 - 8ms/epoch - 2ms/step
Epoch 114/150
4/4 - 0s - loss: 0.4003 - accuracy: 0.9200 - 7ms/epoch - 2ms/step
Epoch 115/150
4/4 - 0s - loss: 0.3973 - accuracy: 0.9200 - 8ms/epoch - 2ms/step
Epoch 116/150
4/4 - 0s - loss: 0.3939 - accuracy: 0.9300 - 7ms/epoch - 2ms/step
Epoch 117/150
4/4 - 0s - loss: 0.3913 

In [28]:
model.predict(scaled_x_test)

array([[2.1125225e-02, 6.6648501e-01, 3.1238979e-01],
       [9.8182023e-01, 1.7995128e-02, 1.8471065e-04],
       [9.5095405e-05, 1.5031324e-01, 8.4959167e-01],
       [1.7558733e-02, 6.4391005e-01, 3.3853117e-01],
       [4.4212528e-03, 4.9410713e-01, 5.0147164e-01],
       [9.6113360e-01, 3.8211267e-02, 6.5516710e-04],
       [7.3928915e-02, 7.7086687e-01, 1.5520418e-01],
       [6.2773371e-04, 2.6949999e-01, 7.2987229e-01],
       [2.6129382e-03, 3.1785232e-01, 6.7953479e-01],
       [3.9127957e-02, 7.1555853e-01, 2.4531351e-01],
       [3.7976583e-03, 4.8328987e-01, 5.1291251e-01],
       [9.7763956e-01, 2.1807212e-02, 5.5328920e-04],
       [9.7996843e-01, 1.9773670e-02, 2.5789294e-04],
       [9.7942138e-01, 2.0119749e-02, 4.5889081e-04],
       [9.9324131e-01, 6.6880146e-03, 7.0717731e-05],
       [2.1881899e-02, 7.3447466e-01, 2.4364345e-01],
       [7.0082705e-04, 2.4612074e-01, 7.5317848e-01],
       [3.9799578e-02, 6.8359798e-01, 2.7660245e-01],
       [3.2621849e-02, 6.912

In [29]:
predicted = np.argmax(model.predict(scaled_x_test),axis=1)
predicted

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [30]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [32]:
confusion_matrix(y_test.argmax(axis=1),predicted)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  1, 15]], dtype=int64)

In [33]:
print(classification_report(y_test.argmax(axis=1),predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.87      0.90        15
           2       0.88      0.94      0.91        16

    accuracy                           0.94        50
   macro avg       0.94      0.93      0.94        50
weighted avg       0.94      0.94      0.94        50



In [34]:
accuracy_score(y_test.argmax(axis=1),predicted)

0.94

In [35]:
#save model
model.save('myfirstmodel.h5')

In [36]:
#load save model
from keras.models import load_model

In [37]:
new_model=load_model('myfirstmodel.h5')

In [38]:
#predict load model
np.argmax(new_model.predict(scaled_x_test),axis=1)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)